#!/usr/bin/env perl

## I would not have thought to write a Perl script in 2018 but here we go ;-)

# Preamble {{{
use strict;
use warnings;
use autodie;
use English qw( -no_match_vars );
use utf8;
use open qw(:std :utf8);
use feature qw(say);
# }}}

use version; our $VERSION = qv('0.9.0');

while (<>) {
    chomp;

    if (not m/^([\#\s]+)(?:'\d{4}'|_|PH|SH|https?:\/\/)/ism and s/^([\#\s]+)('?\w.*)/$1- {'name': $2}/ism) {
        s/(- \{'name': )(\w+)(:)/$1'$2'$3/ism;
        s/(-.*?)': (\[\d+, \d+\])/$1', 'fixed_date': $2/ism;
        s/(-.*?)': (\[\d+, \d+),/$1', 'fixed_date': $2],/ism;
        s/(-.*?)': \[('?[[:alpha:]][\w\s]+'?), (-?\d+)\]?/$1', 'variable_date': $2, 'offset': $3/ism;
        s/(-.*?), (\[(?:'?[\w\s-]+(?:,\s+)?'?)+\])\]?/$1, 'only_states': $2/ism;
        s/(-.*?), 'offset': 0(.*)/$1$2/ism;
    }

    say;
}
